### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by erpadmin** [solarwinds/orionsdk-python#27]
personal information has been replaced
```
(orionsdk) [user@linux-user orionsdk]$ cat otest.py 
import orionsdk

swis = orionsdk.SwisClient("SolarWinds-Orion", "user", "password", verify="server.pem")
swis.query("SELECT NodeID from Orion.Nodes")
```

```
(orionsdk) [user@linux-user orionsdk]$ python otest.py 
/home/user/orionsdk/lib/python2.7/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for solarwinds-orion has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Traceback (most recent call last):
  File "otest.py", line 8, in <module>
    swis.query("SELECT NodeID from Orion.Nodes")
  File "/home/user/orionsdk/lib/python2.7/site-packages/orionsdk/swisclient.py", line 24, in query
    {'query': query, 'parameters': params}).json()
  File "/home/user/orionsdk/lib/python2.7/site-packages/orionsdk/swisclient.py", line 59, in _req
    resp.raise_for_status()
  File "/home/user/orionsdk/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://solarwinds-orion:17778/SolarWinds/InformationService/v3/Json/Query
```

any idea what I need to do to address this issue?

**Comment by erpadmin** [comment]
needed to create and use local Orion account
